resources:
  - namespace.yaml
  - sre-agent.configmap.yaml
  - sre-agent.deployment.yaml
  - sre-agent.service.yaml
  - mcp.services.yaml
  - mcp-k8s.deployment.yaml
  - mcp-logs.deployment.yaml
  - mcp-metrics.deployment.yaml
  - mcp-runbooks.deployment.yaml
