apiVersion: v1
kind: ConfigMap
metadata:
  name: sre-agent-env
  namespace: sre
data:
  LLM_PROVIDER: "groq"
  MCP_K8S_URI: "http://mcp-k8s.sre.svc.cluster.local:3000/mcp"
  MCP_LOGS_URI: "http://mcp-logs.sre.svc.cluster.local:3000/mcp"
  MCP_METRICS_URI: "http://mcp-metrics.sre.svc.cluster.local:3000/mcp"
  MCP_RUNBOOKS_URI: "http://mcp-runbooks.sre.svc.cluster.local:3000/mcp"
